# Generated by Django 2.2.5 on 2019-12-10 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('otherId', models.AutoField(primary_key=True, serialize=False)),
                ('otherName', models.CharField(max_length=50)),
                ('otherDescription', models.CharField(max_length=1000)),
                ('otherPostDate', models.DateField(default=datetime.date.today)),
                ('otherPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('otherPicUrl', models.URLField(blank=True)),
                ('otherCategory', models.CharField(max_length=50)),
                ('otherDetail', models.CharField(max_length=500)),
                ('otherAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseId', models.AutoField(primary_key=True, serialize=False)),
                ('houseName', models.CharField(max_length=50)),
                ('houseDescription', models.CharField(max_length=1000)),
                ('housePostDate', models.DateField(default=datetime.date.today)),
                ('housePrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('housePicUrl', models.URLField(blank=True)),
                ('houseLeasingLength', models.DurationField()),
                ('houseLocation', models.CharField(default='Champaign', max_length=100)),
                ('houseDetail', models.CharField(max_length=500)),
                ('houseAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('clothingId', models.AutoField(primary_key=True, serialize=False)),
                ('clothingName', models.CharField(max_length=50)),
                ('clothingDescription', models.CharField(max_length=1000)),
                ('clothingPostDate', models.DateField(default=datetime.date.today)),
                ('clothingPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('clothingPicUrl', models.URLField(blank=True)),
                ('clothingType', models.CharField(max_length=50)),
                ('clothingSize', models.CharField(max_length=50)),
                ('clothingColor', models.CharField(max_length=50)),
                ('clothingAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=50)),
                ('bookDescription', models.CharField(max_length=1000)),
                ('bookPostDate', models.DateField(default=datetime.date.today)),
                ('bookPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bookPicUrl', models.URLField(blank=True)),
                ('bookTitle', models.CharField(max_length=500)),
                ('bookPublishedAuthor', models.CharField(max_length=50)),
                ('bookPublishedDate', models.DateField(default=datetime.date.today)),
                ('bookAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
    ]
