# Generated by Django 2.2.5 on 2019-12-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carYears',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
